# Default filter config

[bibtype.inproceedings]
required     = [ "author", "booktitle", "title", "year", "publisher", "series", "volume" ]
remove       = [ "address", "doi", "editor", "file", "isbn", "url" ]
fields_order = ["year", "author", "title"]

[bibtype.article]
required = [ "author", "journal", "title", "year" ]
remove   = [ "doi", "isbn", "url" ]

[bibtype.misc]
required = [ "key", "title" ]
